config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "jobs#index"
  resources :jobs

  get "tags/:tag", to: "jobs#index", as: "tag"

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :job_tags, dependent: :destroy
  has_many :tags, through: :job_tags
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 5000 }
  validates :salary, presence: true, numericality: { greater_than: 0 }
  validates :email, presence: true, length: { maximum: 255 }, format: VALID_EMAIL_REGEX
  validates :phone, presence: true
  validates :user_id, presence: true

  def self.tagged_with(name)
    Tag.includes(jobs: :tags).find_by(name: name).jobs
  end

  def all_tags=(names)
    tmp_tags = names.split(',').map do |name|
      Tag.find_or_initialize_by(name: name.strip) unless name.strip.empty?
    end.compact
    self.tags = tmp_tags unless tmp_tags.empty?
  end

  def all_tags
    tags.map(&:name).join(', ')
  end

  def editable_by?(user)
    user && user == author
  end
end

app/models/job_tag.rb
class JobTag < ActiveRecord::Base
  belongs_to :job
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :job_tags, dependent: :destroy
  has_many :jobs, through: :job_tags

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @jobs = params[:tag] ? Job.tagged_with(params[:tag]) : Job.includes(:tags).all
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
    unless @job.editable_by?(current_user)
      redirect_to @job, alert: 'You have no permission to edit it.'
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.author = current_user
    if @job.save
      redirect_to @job
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    unless @job.editable_by?(current_user)
      return redirect_to @job, alert: 'You have no permission to edit it.'
    end

    if @job.update(job_params)
      redirect_to @job
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    unless @job.editable_by?(current_user)
      return redirect_to @job, alert: 'You have no permission to delete it.'
    end

    @job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :salary, :phone, :email, :all_tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert
    result = ""
    bootstrap_alert_type = {notice: :success, alert: :danger}

    flash.each do |msg_type, msg|
      alert_type = bootstrap_alert_type[msg_type.to_sym] || :success
      result << content_tag(:div, class: "container alert alert-#{alert_type}") do
        msg.html_safe <<
        content_tag(:button, "x", class: "close", "data-dismiss" => "alert")
      end
    end

    result.html_safe
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_description(job)
    truncate(job.description, length: 150)
  end

  def tag_link(tag)
    tag_path(tag.name)
  end
end

app/views/common/_error_message.html.erb
<% if job.errors.any? %>
    <div class="alert alert-danger">
      The form contains <%= pluralize(job.errors.count, "error") %>.
    </div>
    <ul class="text-danger">
      <% job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/common/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Rails Bridge Job Board", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Add Job", new_job_path %></li>
        <li>
         <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span>
            Logout
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span>
            Sign up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span>
            Login
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/jobs/_form.html.erb
<%= simple_form_for(job) do |f| %>
  <%= render "common/error_message", job: job %>
  <%= f.input :title %>
  <%= f.input :description, input_html: { size: '60x6' } %>
  <%= f.input :salary, input_html: { step: 1 } %>
  <%= f.input :phone %>
  <%= f.input :email, placeholder: "user@domain.com" %>
  <%= f.input :all_tags, as: :text, placeholder: "tag1, tag2, tag3" %>
  <%= f.submit %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>
<%= render "jobs/form", job: @job %>

app/views/jobs/index.html.erb
<h1>Rails Bridge Open Jobs</h1>
<table class="table" id="jobs_table">
  <thead>
    <th>Job Title</th>
    <th class="no-sort">Job Description</th>
    <th class="no-sort">Tags</th>
    <th>Base Salary</th>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.title, job %></td>
        <td><%= render_job_description(job) %></td>
        <td>
          <% job.tags.each do |tag| %>
            <%= link_to tag.name, tag_link(tag), class: "label label-info" %>
          <% end %>
        </td>
        <td><%= number_to_currency(job.salary, precision: 0) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Add New Job</h1>
<%= render "form", job: @job %>

app/views/jobs/show.html.erb
<h1>
  <%= @job.title %>
  <% if current_user && @job.editable_by?(current_user) %>
    <%= link_to "Delete", @job, method: :delete, class: "btn btn-warning pull-right" %>
    <%= link_to "Edit", edit_job_path(@job), class: "btn btn-primary pull-right" %>
  <% end %>
</h1>
<h2><%= number_to_currency(@job.salary, precision: 0) %> per month</h2>
<%= simple_format(@job.description) %>
<h2>Contact Information</h2>
<ul>
  <li>Email: <%= mail_to(@job.email) %></li>
  <li>Phone: <%= @job.phone %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Bridge Job Board</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'common/nav' %>
<div class="container">
  <%= bootstrap_alert %>
  <%= yield %>
</div>

</body>
</html>